import { Box, Grid, GridItem } from '@chakra-ui/react'
import axios, { AxiosResponse } from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import LocationCard from '../components/location-card'

interface LocationResp {
  locations: any[];
  numberOfLocations: number;
}

const Home: NextPage = () => {
  const [locations, setLocations] = useState([])
  const [payload, setPayload] = useState({ start:0, limit:3 })

  useEffect(() => {
    axios.post('api/locations', payload)
      .then((response: AxiosResponse<any, LocationResp>) => {
        setLocations(response.data.locations)
      })
      .catch(function (error) {
        console.log(error);
      });


  }, [payload])

  console.log('d', locations);
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box height="100%" width="100%">
      <Grid templateColumns='repeat(3, 1fr)' gap={6} padding={6}>
      {locations.map((l, i) => (
        <GridItem w='100%' key={i}>
          <LocationCard location={l} />
        </GridItem>
        ))}
      </Grid>
      </Box>
    </>
  )
}

export default Home
