import { Box } from '@chakra-ui/react'
import axios, { AxiosResponse } from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'

interface LocationResp {
  locations: any[];
  numberOfLocations: number;
}

const Home: NextPage = () => {
  const [locations, setLocations] = useState([])

  useEffect(() => {
    const payload = {start:0, limit:10 };
    axios.post('api/locations', payload)
      .then((response: AxiosResponse<any, LocationResp>) => {
        setLocations(response.data.locations)
      })
      .catch(function (error) {
        console.log(error);
      });


  }, [])

  console.log('d', locations);
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box height="100%" width="100%">
        <p>{JSON.stringify(locations)}</p>
      </Box>
    </>
  )
}

export default Home
